### ISSUE TITLE
Разобраться с консольными ошибками в Firefox

### ISSUE THREAD

**Issue by TatianaFokina** [doka-guide/platform#1260]
## В чём проблема?

Консольные ошибки (без включённых браузерных расширений).

### Firefox

![image](https://github.com/doka-guide/platform/assets/17615202/1b29ec0b-2394-4868-95cf-ba77ff1e5d83)

> InstallTrigger is deprecated and will be removed in the future. [tag.js:177:424](https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js)
>
> Some cookies are misusing the recommended “SameSite“ attribute `4`
>
> Cookie “metrika_enabled” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [tag.js:161:13](https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js)
>
> Cookie “metrika_enabled” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [tag.js:161:13](https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js)
>
> Cookie “_ga_GH8FX28ET0” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 [js:314:899](https://www.googletagmanager.com/gtag/js?id=G-GH8FX28ET0)
>
> Cookie “_ga” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [js:314:899](https://www.googletagmanager.com/gtag/js?id=G-GH8FX28ET0)
>
> Ignoring unsupported entryTypes: longtask. [tag.js:401:56](https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js)
>
> Request to access cookie or storage on “<URL>)” was blocked because it came from a tracker and content blocking is enabled. `2`
>
> Request to access cookie or storage on “https://mc.yandex.ru/watch/83244811?wmode=7&page-url=https%3A%2F%2Fdoka.guide%2F&page-ref=https%3A%2F%2Fdoka.guide%2Fcss%2Fcascade%2F&charset=utf-8&uah=che%0A0&browser-info=pv%3A1%3Avf%3Adgbrch0rxdnnjvl5wkfze2i1r%3Afu%3A0%3Aen%3Autf-8%3Ala%3Aen-US%3Av%3A1310%3Acn%3A1%3Adp%3A0%3Als%3A479049396629%3Ahid%3A953502661%3Az%3A240%3Ai%3A20240415171145%3Aet%3A1713186706%3Ac%3A1%3Arn%3A578489184%3Arqn%3A350%3Au%3A1634062203943616919%3Aw%3A1472x25%3As%3A1472x828x24%3Ask%3A1.3043478260869565%3Afp%3A191%3Awv%3A2%3Ads%3A0%2C0%2C66%2C0%2C2%2C0%2C%2C140%2C2%2C%2C%2C%2C254%3Aco%3A0%3Acpf%3A1%3Ans%3A1713186705692%3Agi%3AR0ExLjEuODc4MzQyOTcwLjE2Nzk5OTIwNDk%3D%3Aadb%3A2%3Afip%3A9631829b64ba2daa0e9a43874b1715ab-0ed8ce9e1e39cec802dafc59181dfc61-a81f3b9bcdd80a361c14af38dc09b309-4bd84c89c35a312599d807af285e7b5f-563c7cc51530c2e907648ea53d7ebd1e-a3fa00e127f881df2924f73305812722-61b9878bbce18de73aafc8582a198c0c-347592ab961f3fadd6faca73161fad65-a81f3b9bcdd80a361c14af38dc09b309-c6d7b47b2dcff33f80cab17f3a360d0b-7a502a49c3fd5ac8d1b845c2031ede1c%3Arqnl%3A1%3Ast%3A1713186706%3At%3A%D0%94%D0%BE%D0%BA%D0%B0&t=gdpr(14)clc(0-0-0)rqnt(1)eco(21037568)aw(1)rcm(0)cdl(na)fip(1)ti(1)” was blocked because it came from a tracker and content blocking is enabled.
> 
> Request to access cookie or storage on “https://mc.yandex.ru/clmap/83244811?page-url=https%3A%2F%2Fdoka.guide%2Fcss%2Fcascade%2F&pointer-click=rn%3A594426269%3Ax%3A26410%3Ay%3A50461%3At%3A44%3Ap%3AA1%3BQdA%7F%3AX%3A153%3AY%3A41&browser-info=u%3A1634062203943616919%3Av%3A1310%3Avf%3Adgbrch0rxdnnjvl5wkfze2i1r%3Arqnl%3A2%3Ast%3A1713186706&t=gdpr(14)ti(1)” was blocked because it came from a tracker and content blocking is enabled.
>
>The resource at “https://doka.guide/fonts/graphik/graphik-regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [doka.guide](https://doka.guide/)
>
>The resource at “https://doka.guide/fonts/spot-mono/spot-mono-light.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [doka.guide](https://doka.guide/)

## Chrome

![image](https://github.com/doka-guide/platform/assets/17615202/6ea6c56b-0648-4519-a8b5-db6ac72aa642)

> Uncaught (in promise) TypeError: s.request.startsWith is not a function
>     at sw.js:1:11550
>     at Generator.next (<anonymous>)
>     at sw.js:1:196
>     at new Promise (<anonymous>)
>     at o (sw.js:1:16)
>     at sw.js:1:11512
>
> The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
>
> 8sw.js:1 Uncaught (in promise) TypeError: s.request.startsWith is not a function
>     at sw.js:1:11550
>     at Generator.next (<anonymous>)
>     at sw.js:1:196
>     at new Promise (<anonymous>)
>     at o (sw.js:1:16)
>     at sw.js:1:11512
> js:1 
> 
> Failed to load resource: net::ERR_NAME_NOT_RESOLVED
> tag.js:1 
>         
> Failed to load resource: net::ERR_NAME_NOT_RESOLVED
>
> 7sw.js:1 Uncaught (in promise) TypeError: s.request.startsWith is not a function
>     at sw.js:1:11550
>     at Generator.next (<anonymous>)
>     at sw.js:1:196
>     at new Promise (<anonymous>)
>     at o (sw.js:1:16)
>     at sw.js:1:11512

### InstallTrigger

Не использовать вообще.

- [Deprecate InstallTrigger](https://bugzilla.mozilla.org/show_bug.cgi?id=1754441), Bugzilla
- [Intent to deprecate InstallTrigger](https://groups.google.com/a/mozilla.org/g/dev-platform/c/O8xtLi1W0Q8/m/-iD282tLDAAJ), Google Chrome Groups

### SameSite cookies

Issues with blocked SameSite cookies in local development environments can be fixed by temporarily disabling sameSite policies in Firefox and Chrome.

- [I got 99 problems but `SameSite` cookies ain't one](https://timdaub.github.io/2020/12/03/samesite/)
- [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value)

### Blocked request to access cookie or storage

This is broken on Firefox 109 and later. Individual sites can be allowlisted by users by disabling Enhanced Tracking Protection for the given site. This can be done via the toggle in the shield panel or via "Manage Exceptions" in about:preferences#privacy.

- [Best practices for using signInWithRedirect on browsers that block third-party storage access](https://firebase.google.com/docs/auth/web/redirect-best-practices)

### Link preload was not used

Typically you need to include crossorigin in your preload. Check to see if the font loads twice in the network report. If it does, add/remove crossorigin and it may fix it.

Also check that the preload uses as="font" type="font/woff2".

- [Dev tools console warning message - resource preload a few seconds](https://support.google.com/webmasters/thread/179310181/dev-tools-console-warning-message-resource-preload-a-few-seconds?hl=en)

**Comment by loonlylokly** [comment]
У меня точно такие же ошибки вылизают. А также при попытке нажать на кнопки в форме "Была ли статья полезной?" Вылизает ошибка отправки формы.
Эта ошибка вылизает и в linux firefox и в linux chromium. (Однако в приватном окне хромиума вроде все нормально работает) Расширения в хромиуме были все отключены.

index-e2e2677516.js:30
SyntaxError: Unexpected end of JSON input
    at index-e2e2677516.js:30:4825
    
![image](https://github.com/doka-guide/platform/assets/30442282/0710e84e-6714-48c4-87a9-9f3e15cd001a)

**Comment by furtivite** [comment]
В Safari на главной нет ошибки, но если перейти на любую страницу другую, будет ошибка, при возврате оттуда на главную сохраняется и на главной.

<img width="1765" alt="Снимок экрана 2025-01-13 в 14 53 02" src="https://github.com/user-attachments/assets/a9a40498-4d6a-4238-97fe-47f05f5eeb3e" />

<img width="1765" alt="Снимок экрана 2025-01-13 в 14 53 07" src="https://github.com/user-attachments/assets/79b19916-c1f1-4a09-8cdb-fc814fd532bf" />
