### ISSUE TITLE
Ошибка в скрипте предпросмотра статьи

### ISSUE THREAD

**Issue by nsbarsukov** [doka-guide/platform#960]
## Описание проблемы
Используя вот [эту инструкцию](https://github.com/doka-guide/content/blob/main/docs/preview.md), запускаю докер и затем запускаю скрипт.

Скрипт падает с ошибкой `HttpError: This endpoint requires you to be authenticated.`
<details>
<summary>Смотреть длинные логи этой ошибки</summary>

```sh
Вы запускаете платформу Доки. Docker уже запущен? (y/n) y
Запустить веб-сервер на http://localhost:8080? (y/n) y
Остановить веб-сервер можно с помощью клавиш: Ctrl + c$
Using default tag: latest
latest: Pulling from dokaguide/platform
Digest: sha256:672273917ff799cae1311d7af7b09aa263f8b1f0944b18b21b7a69d7a08f112f
Status: Image is up to date for dokaguide/platform:latest
docker.io/dokaguide/platform:latest

> start
> cross-env-shell NODE_ENV=development "npm run make-links && eleventy --serve --quiet"


> make-links
> node make-links.js

Использую настройки из .env
Проверяю, установлены ли символические ссылки к src/html, src/css, src/js, src/tools, src/recipes, src/people, src/pages, src/settings
Удаляю старую ссылку src/html
Удаляю старую ссылку src/css
Удаляю старую ссылку src/js
Удаляю старую ссылку src/tools
Удаляю старую ссылку src/recipes
Удаляю старую ссылку src/people
Удаляю старую ссылку src/pages
Удаляю старую ссылку src/settings
Удаляю старый каталог src/html
Удаляю старый каталог src/css
Удаляю старый каталог src/js
Удаляю старый каталог src/tools
Удаляю старый каталог src/recipes
Удаляю старый каталог src/people
Удаляю старый каталог src/pages
Удаляю старый каталог src/settings
Создаю симлинки:
src/html → ../content/html
src/css → ../content/css
src/js → ../content/js
src/tools → ../content/tools
src/recipes → ../content/recipes
src/people → ../content/people
src/pages → ../content/pages
src/settings → ../content/settings
✅ Готово
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] > This endpoint requires you to be authenticated.

`HttpError` was thrown:
[11ty]     HttpError: This endpoint requires you to be authenticated.
        at /platform/node_modules/@octokit/request/dist-node/index.js:86:21
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 1)
        at async getAuthorsContribution (/platform/src/libs/github-contribution-service/github-contribution-service.js:56:39)
[11ty] Copied 1222 files / Wrote 0 files in 30.44 seconds (v1.0.0)
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.15.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>
npm notice Run `npm install -g npm@8.15.0` to update!
npm notice 
Спасибо за ваш труд!

```

</details>

Не знаю, где он просит меня авторизоваться :(

## Ожидаемое поведение
Cкрипт не падает с ошибкой или в документацию добавлен раздел **Troubleshooting**, в котором рассказывается о возможном решении данной проблемы.

## Немного информации, которая может быть полезна
* MacBook Pro (16-inch, 2019), Intel, MacOS Monterey
* Docker Desktop 4.10.1 (82475)

**Comment by nsbarsukov** [comment]
Логи ошибки ведут сюда

https://github.com/doka-guide/platform/blob/791add1e44d2289d9ef88afcbd7f20e79463a9d2/src/libs/github-contribution-service/github-contribution-service.js#L56-L59

**Comment by igsekor** [comment]
Спасибо! Посмотрим, что работает не так, как ожидалось :)
